//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3615
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wizard {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandBar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandBar() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wizard.CommandBar", typeof(CommandBar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aktion.
        /// </summary>
        internal static string deAction {
            get {
                return ResourceManager.GetString("deAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add-Ins.
        /// </summary>
        internal static string deAddins {
            get {
                return ResourceManager.GetString("deAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analysieren.
        /// </summary>
        internal static string deAnalyze {
            get {
                return ResourceManager.GetString("deAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Erstellen.
        /// </summary>
        internal static string deBuild {
            get {
                return ResourceManager.GetString("deBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Klassendiagramm.
        /// </summary>
        internal static string deClass_Diagram {
            get {
                return ResourceManager.GetString("deClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Community.
        /// </summary>
        internal static string deCommunity {
            get {
                return ResourceManager.GetString("deCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Daten.
        /// </summary>
        internal static string deData {
            get {
                return ResourceManager.GetString("deData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datenbank.
        /// </summary>
        internal static string deDatabase {
            get {
                return ResourceManager.GetString("deDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datenbankdiagramm.
        /// </summary>
        internal static string deDatabase_Diagram {
            get {
                return ResourceManager.GetString("deDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debuggen.
        /// </summary>
        internal static string deDebug {
            get {
                return ResourceManager.GetString("deDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diagramm.
        /// </summary>
        internal static string deDiagram {
            get {
                return ResourceManager.GetString("deDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bearbeiten.
        /// </summary>
        internal static string deEdit {
            get {
                return ResourceManager.GetString("deEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datei.
        /// </summary>
        internal static string deFile {
            get {
                return ResourceManager.GetString("deFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Format.
        /// </summary>
        internal static string deFormat {
            get {
                return ResourceManager.GetString("deFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rahmen.
        /// </summary>
        internal static string deFrames {
            get {
                return ResourceManager.GetString("deFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hilfe.
        /// </summary>
        internal static string deHelp {
            get {
                return ResourceManager.GetString("deHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bild.
        /// </summary>
        internal static string deImage {
            get {
                return ResourceManager.GetString("deImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Layout.
        /// </summary>
        internal static string deLayout {
            get {
                return ResourceManager.GetString("deLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Makros.
        /// </summary>
        internal static string deMacros {
            get {
                return ResourceManager.GetString("deMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Projekt.
        /// </summary>
        internal static string deProject {
            get {
                return ResourceManager.GetString("deProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query.
        /// </summary>
        internal static string deQuery {
            get {
                return ResourceManager.GetString("deQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abfrage-Designer.
        /// </summary>
        internal static string deQuery_Designer {
            get {
                return ResourceManager.GetString("deQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Umgestalten.
        /// </summary>
        internal static string deRefactor {
            get {
                return ResourceManager.GetString("deRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bericht.
        /// </summary>
        internal static string deReport {
            get {
                return ResourceManager.GetString("deReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ressourcen.
        /// </summary>
        internal static string deResources {
            get {
                return ResourceManager.GetString("deResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Schema.
        /// </summary>
        internal static string deSchema {
            get {
                return ResourceManager.GetString("deSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formate.
        /// </summary>
        internal static string deStyles {
            get {
                return ResourceManager.GetString("deStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabelle.
        /// </summary>
        internal static string deTable {
            get {
                return ResourceManager.GetString("deTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabellen-Designer.
        /// </summary>
        internal static string deTable_Designer {
            get {
                return ResourceManager.GetString("deTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Team.
        /// </summary>
        internal static string deTeam {
            get {
                return ResourceManager.GetString("deTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Testen.
        /// </summary>
        internal static string deTest {
            get {
                return ResourceManager.GetString("deTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extras.
        /// </summary>
        internal static string deTools {
            get {
                return ResourceManager.GetString("deTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ansicht.
        /// </summary>
        internal static string deView {
            get {
                return ResourceManager.GetString("deView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fenster.
        /// </summary>
        internal static string deWindow {
            get {
                return ResourceManager.GetString("deWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XML.
        /// </summary>
        internal static string deXML {
            get {
                return ResourceManager.GetString("deXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action.
        /// </summary>
        internal static string enAction {
            get {
                return ResourceManager.GetString("enAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Addins.
        /// </summary>
        internal static string enAddins {
            get {
                return ResourceManager.GetString("enAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analyze.
        /// </summary>
        internal static string enAnalyze {
            get {
                return ResourceManager.GetString("enAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Build.
        /// </summary>
        internal static string enBuild {
            get {
                return ResourceManager.GetString("enBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Class Diagram.
        /// </summary>
        internal static string enClass_Diagram {
            get {
                return ResourceManager.GetString("enClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Community.
        /// </summary>
        internal static string enCommunity {
            get {
                return ResourceManager.GetString("enCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data.
        /// </summary>
        internal static string enData {
            get {
                return ResourceManager.GetString("enData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database.
        /// </summary>
        internal static string enDatabase {
            get {
                return ResourceManager.GetString("enDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database Diagram.
        /// </summary>
        internal static string enDatabase_Diagram {
            get {
                return ResourceManager.GetString("enDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debug.
        /// </summary>
        internal static string enDebug {
            get {
                return ResourceManager.GetString("enDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diagram.
        /// </summary>
        internal static string enDiagram {
            get {
                return ResourceManager.GetString("enDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        internal static string enEdit {
            get {
                return ResourceManager.GetString("enEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File.
        /// </summary>
        internal static string enFile {
            get {
                return ResourceManager.GetString("enFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Format.
        /// </summary>
        internal static string enFormat {
            get {
                return ResourceManager.GetString("enFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frames.
        /// </summary>
        internal static string enFrames {
            get {
                return ResourceManager.GetString("enFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        internal static string enHelp {
            get {
                return ResourceManager.GetString("enHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image.
        /// </summary>
        internal static string enImage {
            get {
                return ResourceManager.GetString("enImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Layout.
        /// </summary>
        internal static string enLayout {
            get {
                return ResourceManager.GetString("enLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Macros.
        /// </summary>
        internal static string enMacros {
            get {
                return ResourceManager.GetString("enMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Project.
        /// </summary>
        internal static string enProject {
            get {
                return ResourceManager.GetString("enProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query.
        /// </summary>
        internal static string enQuery {
            get {
                return ResourceManager.GetString("enQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query Designer.
        /// </summary>
        internal static string enQuery_Designer {
            get {
                return ResourceManager.GetString("enQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refactor.
        /// </summary>
        internal static string enRefactor {
            get {
                return ResourceManager.GetString("enRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report.
        /// </summary>
        internal static string enReport {
            get {
                return ResourceManager.GetString("enReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resources.
        /// </summary>
        internal static string enResources {
            get {
                return ResourceManager.GetString("enResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Schema.
        /// </summary>
        internal static string enSchema {
            get {
                return ResourceManager.GetString("enSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Styles.
        /// </summary>
        internal static string enStyles {
            get {
                return ResourceManager.GetString("enStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Table.
        /// </summary>
        internal static string enTable {
            get {
                return ResourceManager.GetString("enTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Table Designer.
        /// </summary>
        internal static string enTable_Designer {
            get {
                return ResourceManager.GetString("enTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Team.
        /// </summary>
        internal static string enTeam {
            get {
                return ResourceManager.GetString("enTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test.
        /// </summary>
        internal static string enTest {
            get {
                return ResourceManager.GetString("enTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tools.
        /// </summary>
        internal static string enTools {
            get {
                return ResourceManager.GetString("enTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View.
        /// </summary>
        internal static string enView {
            get {
                return ResourceManager.GetString("enView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Window.
        /// </summary>
        internal static string enWindow {
            get {
                return ResourceManager.GetString("enWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XML.
        /// </summary>
        internal static string enXML {
            get {
                return ResourceManager.GetString("enXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción.
        /// </summary>
        internal static string esAction {
            get {
                return ResourceManager.GetString("esAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complementos.
        /// </summary>
        internal static string esAddins {
            get {
                return ResourceManager.GetString("esAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analizar.
        /// </summary>
        internal static string esAnalyze {
            get {
                return ResourceManager.GetString("esAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar.
        /// </summary>
        internal static string esBuild {
            get {
                return ResourceManager.GetString("esBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diagrama de clase.
        /// </summary>
        internal static string esClass_Diagram {
            get {
                return ResourceManager.GetString("esClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comunidad.
        /// </summary>
        internal static string esCommunity {
            get {
                return ResourceManager.GetString("esCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos.
        /// </summary>
        internal static string esData {
            get {
                return ResourceManager.GetString("esData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base de datos.
        /// </summary>
        internal static string esDatabase {
            get {
                return ResourceManager.GetString("esDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diagrama de base de datos.
        /// </summary>
        internal static string esDatabase_Diagram {
            get {
                return ResourceManager.GetString("esDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Depurar.
        /// </summary>
        internal static string esDebug {
            get {
                return ResourceManager.GetString("esDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diagrama.
        /// </summary>
        internal static string esDiagram {
            get {
                return ResourceManager.GetString("esDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string esEdit {
            get {
                return ResourceManager.GetString("esEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo.
        /// </summary>
        internal static string esFile {
            get {
                return ResourceManager.GetString("esFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato.
        /// </summary>
        internal static string esFormat {
            get {
                return ResourceManager.GetString("esFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcos.
        /// </summary>
        internal static string esFrames {
            get {
                return ResourceManager.GetString("esFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        internal static string esHelp {
            get {
                return ResourceManager.GetString("esHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen.
        /// </summary>
        internal static string esImage {
            get {
                return ResourceManager.GetString("esImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diseño.
        /// </summary>
        internal static string esLayout {
            get {
                return ResourceManager.GetString("esLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Macros.
        /// </summary>
        internal static string esMacros {
            get {
                return ResourceManager.GetString("esMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto.
        /// </summary>
        internal static string esProject {
            get {
                return ResourceManager.GetString("esProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta.
        /// </summary>
        internal static string esQuery {
            get {
                return ResourceManager.GetString("esQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diseñador de consultas.
        /// </summary>
        internal static string esQuery_Designer {
            get {
                return ResourceManager.GetString("esQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refactorizar.
        /// </summary>
        internal static string esRefactor {
            get {
                return ResourceManager.GetString("esRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informe.
        /// </summary>
        internal static string esReport {
            get {
                return ResourceManager.GetString("esReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recursos.
        /// </summary>
        internal static string esResources {
            get {
                return ResourceManager.GetString("esResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esquema.
        /// </summary>
        internal static string esSchema {
            get {
                return ResourceManager.GetString("esSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estilos.
        /// </summary>
        internal static string esStyles {
            get {
                return ResourceManager.GetString("esStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla.
        /// </summary>
        internal static string esTable {
            get {
                return ResourceManager.GetString("esTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diseñador de tablas.
        /// </summary>
        internal static string esTable_Designer {
            get {
                return ResourceManager.GetString("esTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipo.
        /// </summary>
        internal static string esTeam {
            get {
                return ResourceManager.GetString("esTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba.
        /// </summary>
        internal static string esTest {
            get {
                return ResourceManager.GetString("esTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Herramientas.
        /// </summary>
        internal static string esTools {
            get {
                return ResourceManager.GetString("esTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        internal static string esView {
            get {
                return ResourceManager.GetString("esView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventana.
        /// </summary>
        internal static string esWindow {
            get {
                return ResourceManager.GetString("esWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XML.
        /// </summary>
        internal static string esXML {
            get {
                return ResourceManager.GetString("esXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action.
        /// </summary>
        internal static string frAction {
            get {
                return ResourceManager.GetString("frAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compléments.
        /// </summary>
        internal static string frAddins {
            get {
                return ResourceManager.GetString("frAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analyser.
        /// </summary>
        internal static string frAnalyze {
            get {
                return ResourceManager.GetString("frAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Générer.
        /// </summary>
        internal static string frBuild {
            get {
                return ResourceManager.GetString("frBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diagramme de classes.
        /// </summary>
        internal static string frClass_Diagram {
            get {
                return ResourceManager.GetString("frClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Communauté.
        /// </summary>
        internal static string frCommunity {
            get {
                return ResourceManager.GetString("frCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Données.
        /// </summary>
        internal static string frData {
            get {
                return ResourceManager.GetString("frData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base de données.
        /// </summary>
        internal static string frDatabase {
            get {
                return ResourceManager.GetString("frDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Schéma de base de données.
        /// </summary>
        internal static string frDatabase_Diagram {
            get {
                return ResourceManager.GetString("frDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Déboguer.
        /// </summary>
        internal static string frDebug {
            get {
                return ResourceManager.GetString("frDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Schéma.
        /// </summary>
        internal static string frDiagram {
            get {
                return ResourceManager.GetString("frDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modifier.
        /// </summary>
        internal static string frEdit {
            get {
                return ResourceManager.GetString("frEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fichier.
        /// </summary>
        internal static string frFile {
            get {
                return ResourceManager.GetString("frFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Format.
        /// </summary>
        internal static string frFormat {
            get {
                return ResourceManager.GetString("frFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frames.
        /// </summary>
        internal static string frFrames {
            get {
                return ResourceManager.GetString("frFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ?.
        /// </summary>
        internal static string frHelp {
            get {
                return ResourceManager.GetString("frHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image.
        /// </summary>
        internal static string frImage {
            get {
                return ResourceManager.GetString("frImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disposition.
        /// </summary>
        internal static string frLayout {
            get {
                return ResourceManager.GetString("frLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Macros.
        /// </summary>
        internal static string frMacros {
            get {
                return ResourceManager.GetString("frMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Projet.
        /// </summary>
        internal static string frProject {
            get {
                return ResourceManager.GetString("frProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requête.
        /// </summary>
        internal static string frQuery {
            get {
                return ResourceManager.GetString("frQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concepteur de requêtes.
        /// </summary>
        internal static string frQuery_Designer {
            get {
                return ResourceManager.GetString("frQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refactoriser.
        /// </summary>
        internal static string frRefactor {
            get {
                return ResourceManager.GetString("frRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rapport.
        /// </summary>
        internal static string frReport {
            get {
                return ResourceManager.GetString("frReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ressources.
        /// </summary>
        internal static string frResources {
            get {
                return ResourceManager.GetString("frResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Schéma.
        /// </summary>
        internal static string frSchema {
            get {
                return ResourceManager.GetString("frSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Styles.
        /// </summary>
        internal static string frStyles {
            get {
                return ResourceManager.GetString("frStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tableau.
        /// </summary>
        internal static string frTable {
            get {
                return ResourceManager.GetString("frTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concepteur de tables.
        /// </summary>
        internal static string frTable_Designer {
            get {
                return ResourceManager.GetString("frTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a équipe.
        /// </summary>
        internal static string frTeam {
            get {
                return ResourceManager.GetString("frTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test.
        /// </summary>
        internal static string frTest {
            get {
                return ResourceManager.GetString("frTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Outils.
        /// </summary>
        internal static string frTools {
            get {
                return ResourceManager.GetString("frTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Affichage.
        /// </summary>
        internal static string frView {
            get {
                return ResourceManager.GetString("frView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fenêtre.
        /// </summary>
        internal static string frWindow {
            get {
                return ResourceManager.GetString("frWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XML.
        /// </summary>
        internal static string frXML {
            get {
                return ResourceManager.GetString("frXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Azione.
        /// </summary>
        internal static string itAction {
            get {
                return ResourceManager.GetString("itAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Componenti aggiuntivi.
        /// </summary>
        internal static string itAddins {
            get {
                return ResourceManager.GetString("itAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analizza.
        /// </summary>
        internal static string itAnalyze {
            get {
                return ResourceManager.GetString("itAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Genera.
        /// </summary>
        internal static string itBuild {
            get {
                return ResourceManager.GetString("itBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diagramma classi.
        /// </summary>
        internal static string itClass_Diagram {
            get {
                return ResourceManager.GetString("itClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comunità.
        /// </summary>
        internal static string itCommunity {
            get {
                return ResourceManager.GetString("itCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dati.
        /// </summary>
        internal static string itData {
            get {
                return ResourceManager.GetString("itData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database.
        /// </summary>
        internal static string itDatabase {
            get {
                return ResourceManager.GetString("itDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diagramma database.
        /// </summary>
        internal static string itDatabase_Diagram {
            get {
                return ResourceManager.GetString("itDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debug.
        /// </summary>
        internal static string itDebug {
            get {
                return ResourceManager.GetString("itDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diagramma.
        /// </summary>
        internal static string itDiagram {
            get {
                return ResourceManager.GetString("itDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modifica.
        /// </summary>
        internal static string itEdit {
            get {
                return ResourceManager.GetString("itEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File.
        /// </summary>
        internal static string itFile {
            get {
                return ResourceManager.GetString("itFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato.
        /// </summary>
        internal static string itFormat {
            get {
                return ResourceManager.GetString("itFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frame.
        /// </summary>
        internal static string itFrames {
            get {
                return ResourceManager.GetString("itFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ?.
        /// </summary>
        internal static string itHelp {
            get {
                return ResourceManager.GetString("itHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Immagine.
        /// </summary>
        internal static string itImage {
            get {
                return ResourceManager.GetString("itImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Layout.
        /// </summary>
        internal static string itLayout {
            get {
                return ResourceManager.GetString("itLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Macro.
        /// </summary>
        internal static string itMacros {
            get {
                return ResourceManager.GetString("itMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Progetto.
        /// </summary>
        internal static string itProject {
            get {
                return ResourceManager.GetString("itProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query.
        /// </summary>
        internal static string itQuery {
            get {
                return ResourceManager.GetString("itQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Progettazione query.
        /// </summary>
        internal static string itQuery_Designer {
            get {
                return ResourceManager.GetString("itQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Effettua refactoring.
        /// </summary>
        internal static string itRefactor {
            get {
                return ResourceManager.GetString("itRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report.
        /// </summary>
        internal static string itReport {
            get {
                return ResourceManager.GetString("itReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Risorse.
        /// </summary>
        internal static string itResources {
            get {
                return ResourceManager.GetString("itResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Schema.
        /// </summary>
        internal static string itSchema {
            get {
                return ResourceManager.GetString("itSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stili.
        /// </summary>
        internal static string itStyles {
            get {
                return ResourceManager.GetString("itStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabella.
        /// </summary>
        internal static string itTable {
            get {
                return ResourceManager.GetString("itTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Progettazione tabelle.
        /// </summary>
        internal static string itTable_Designer {
            get {
                return ResourceManager.GetString("itTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Team.
        /// </summary>
        internal static string itTeam {
            get {
                return ResourceManager.GetString("itTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prova.
        /// </summary>
        internal static string itTest {
            get {
                return ResourceManager.GetString("itTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Strumenti.
        /// </summary>
        internal static string itTools {
            get {
                return ResourceManager.GetString("itTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visualizza.
        /// </summary>
        internal static string itView {
            get {
                return ResourceManager.GetString("itView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finestra.
        /// </summary>
        internal static string itWindow {
            get {
                return ResourceManager.GetString("itWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XML.
        /// </summary>
        internal static string itXML {
            get {
                return ResourceManager.GetString("itXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 操作.
        /// </summary>
        internal static string jaAction {
            get {
                return ResourceManager.GetString("jaAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a アドイン.
        /// </summary>
        internal static string jaAddins {
            get {
                return ResourceManager.GetString("jaAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 分析.
        /// </summary>
        internal static string jaAnalyze {
            get {
                return ResourceManager.GetString("jaAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ビルド.
        /// </summary>
        internal static string jaBuild {
            get {
                return ResourceManager.GetString("jaBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a クラス ダイアグラム.
        /// </summary>
        internal static string jaClass_Diagram {
            get {
                return ResourceManager.GetString("jaClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a コミュニティ.
        /// </summary>
        internal static string jaCommunity {
            get {
                return ResourceManager.GetString("jaCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a データ.
        /// </summary>
        internal static string jaData {
            get {
                return ResourceManager.GetString("jaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a データベース.
        /// </summary>
        internal static string jaDatabase {
            get {
                return ResourceManager.GetString("jaDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a データベース ダイアグラム.
        /// </summary>
        internal static string jaDatabase_Diagram {
            get {
                return ResourceManager.GetString("jaDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a デバッグ.
        /// </summary>
        internal static string jaDebug {
            get {
                return ResourceManager.GetString("jaDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ダイアグラム.
        /// </summary>
        internal static string jaDiagram {
            get {
                return ResourceManager.GetString("jaDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 編集.
        /// </summary>
        internal static string jaEdit {
            get {
                return ResourceManager.GetString("jaEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ファイル.
        /// </summary>
        internal static string jaFile {
            get {
                return ResourceManager.GetString("jaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 書式.
        /// </summary>
        internal static string jaFormat {
            get {
                return ResourceManager.GetString("jaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a フレーム.
        /// </summary>
        internal static string jaFrames {
            get {
                return ResourceManager.GetString("jaFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ヘルプ.
        /// </summary>
        internal static string jaHelp {
            get {
                return ResourceManager.GetString("jaHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a イメージ.
        /// </summary>
        internal static string jaImage {
            get {
                return ResourceManager.GetString("jaImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a レイアウト.
        /// </summary>
        internal static string jaLayout {
            get {
                return ResourceManager.GetString("jaLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a マクロ.
        /// </summary>
        internal static string jaMacros {
            get {
                return ResourceManager.GetString("jaMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a プロジェクト.
        /// </summary>
        internal static string jaProject {
            get {
                return ResourceManager.GetString("jaProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a クエリ.
        /// </summary>
        internal static string jaQuery {
            get {
                return ResourceManager.GetString("jaQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a クエリ デザイナ.
        /// </summary>
        internal static string jaQuery_Designer {
            get {
                return ResourceManager.GetString("jaQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a リファクタ.
        /// </summary>
        internal static string jaRefactor {
            get {
                return ResourceManager.GetString("jaRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a レポート.
        /// </summary>
        internal static string jaReport {
            get {
                return ResourceManager.GetString("jaReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a リソース.
        /// </summary>
        internal static string jaResources {
            get {
                return ResourceManager.GetString("jaResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a スキーマ.
        /// </summary>
        internal static string jaSchema {
            get {
                return ResourceManager.GetString("jaSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a スタイル.
        /// </summary>
        internal static string jaStyles {
            get {
                return ResourceManager.GetString("jaStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a テーブル.
        /// </summary>
        internal static string jaTable {
            get {
                return ResourceManager.GetString("jaTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a テーブル デザイナ.
        /// </summary>
        internal static string jaTable_Designer {
            get {
                return ResourceManager.GetString("jaTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a チーム.
        /// </summary>
        internal static string jaTeam {
            get {
                return ResourceManager.GetString("jaTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a テスト.
        /// </summary>
        internal static string jaTest {
            get {
                return ResourceManager.GetString("jaTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ツール.
        /// </summary>
        internal static string jaTools {
            get {
                return ResourceManager.GetString("jaTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 表示.
        /// </summary>
        internal static string jaView {
            get {
                return ResourceManager.GetString("jaView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ウィンドウ.
        /// </summary>
        internal static string jaWindow {
            get {
                return ResourceManager.GetString("jaWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XML.
        /// </summary>
        internal static string jaXML {
            get {
                return ResourceManager.GetString("jaXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 작업.
        /// </summary>
        internal static string koAction {
            get {
                return ResourceManager.GetString("koAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 추가 기능.
        /// </summary>
        internal static string koAddins {
            get {
                return ResourceManager.GetString("koAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 분석.
        /// </summary>
        internal static string koAnalyze {
            get {
                return ResourceManager.GetString("koAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 빌드.
        /// </summary>
        internal static string koBuild {
            get {
                return ResourceManager.GetString("koBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 클래스 다이어그램.
        /// </summary>
        internal static string koClass_Diagram {
            get {
                return ResourceManager.GetString("koClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 커뮤니티.
        /// </summary>
        internal static string koCommunity {
            get {
                return ResourceManager.GetString("koCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 데이터.
        /// </summary>
        internal static string koData {
            get {
                return ResourceManager.GetString("koData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 데이터베이스.
        /// </summary>
        internal static string koDatabase {
            get {
                return ResourceManager.GetString("koDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 데이터베이스 다이어그램.
        /// </summary>
        internal static string koDatabase_Diagram {
            get {
                return ResourceManager.GetString("koDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 디버그.
        /// </summary>
        internal static string koDebug {
            get {
                return ResourceManager.GetString("koDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 다이어그램.
        /// </summary>
        internal static string koDiagram {
            get {
                return ResourceManager.GetString("koDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 편집.
        /// </summary>
        internal static string koEdit {
            get {
                return ResourceManager.GetString("koEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 파일.
        /// </summary>
        internal static string koFile {
            get {
                return ResourceManager.GetString("koFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 서식.
        /// </summary>
        internal static string koFormat {
            get {
                return ResourceManager.GetString("koFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 프레임.
        /// </summary>
        internal static string koFrames {
            get {
                return ResourceManager.GetString("koFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 도움말.
        /// </summary>
        internal static string koHelp {
            get {
                return ResourceManager.GetString("koHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 이미지.
        /// </summary>
        internal static string koImage {
            get {
                return ResourceManager.GetString("koImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 레이아웃.
        /// </summary>
        internal static string koLayout {
            get {
                return ResourceManager.GetString("koLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 매크로.
        /// </summary>
        internal static string koMacros {
            get {
                return ResourceManager.GetString("koMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 프로젝트.
        /// </summary>
        internal static string koProject {
            get {
                return ResourceManager.GetString("koProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 쿼리.
        /// </summary>
        internal static string koQuery {
            get {
                return ResourceManager.GetString("koQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 쿼리 디자이너.
        /// </summary>
        internal static string koQuery_Designer {
            get {
                return ResourceManager.GetString("koQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 리팩터링.
        /// </summary>
        internal static string koRefactor {
            get {
                return ResourceManager.GetString("koRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 보고서.
        /// </summary>
        internal static string koReport {
            get {
                return ResourceManager.GetString("koReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 리소스.
        /// </summary>
        internal static string koResources {
            get {
                return ResourceManager.GetString("koResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 스키마.
        /// </summary>
        internal static string koSchema {
            get {
                return ResourceManager.GetString("koSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 스타일.
        /// </summary>
        internal static string koStyles {
            get {
                return ResourceManager.GetString("koStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 테이블.
        /// </summary>
        internal static string koTable {
            get {
                return ResourceManager.GetString("koTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 테이블 디자이너.
        /// </summary>
        internal static string koTable_Designer {
            get {
                return ResourceManager.GetString("koTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 팀.
        /// </summary>
        internal static string koTeam {
            get {
                return ResourceManager.GetString("koTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 테스트.
        /// </summary>
        internal static string koTest {
            get {
                return ResourceManager.GetString("koTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 도구.
        /// </summary>
        internal static string koTools {
            get {
                return ResourceManager.GetString("koTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 뷰.
        /// </summary>
        internal static string koView {
            get {
                return ResourceManager.GetString("koView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 창.
        /// </summary>
        internal static string koWindow {
            get {
                return ResourceManager.GetString("koWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XML.
        /// </summary>
        internal static string koXML {
            get {
                return ResourceManager.GetString("koXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 操作.
        /// </summary>
        internal static string zh_CHSAction {
            get {
                return ResourceManager.GetString("zh-CHSAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 外接程序.
        /// </summary>
        internal static string zh_CHSAddins {
            get {
                return ResourceManager.GetString("zh-CHSAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 分析.
        /// </summary>
        internal static string zh_CHSAnalyze {
            get {
                return ResourceManager.GetString("zh-CHSAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 生成.
        /// </summary>
        internal static string zh_CHSBuild {
            get {
                return ResourceManager.GetString("zh-CHSBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 类关系图.
        /// </summary>
        internal static string zh_CHSClass_Diagram {
            get {
                return ResourceManager.GetString("zh-CHSClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 社区.
        /// </summary>
        internal static string zh_CHSCommunity {
            get {
                return ResourceManager.GetString("zh-CHSCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 数据.
        /// </summary>
        internal static string zh_CHSData {
            get {
                return ResourceManager.GetString("zh-CHSData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 数据库.
        /// </summary>
        internal static string zh_CHSDatabase {
            get {
                return ResourceManager.GetString("zh-CHSDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 数据库关系图.
        /// </summary>
        internal static string zh_CHSDatabase_Diagram {
            get {
                return ResourceManager.GetString("zh-CHSDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 调试.
        /// </summary>
        internal static string zh_CHSDebug {
            get {
                return ResourceManager.GetString("zh-CHSDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 关系图.
        /// </summary>
        internal static string zh_CHSDiagram {
            get {
                return ResourceManager.GetString("zh-CHSDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 编辑.
        /// </summary>
        internal static string zh_CHSEdit {
            get {
                return ResourceManager.GetString("zh-CHSEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 文件.
        /// </summary>
        internal static string zh_CHSFile {
            get {
                return ResourceManager.GetString("zh-CHSFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 格式.
        /// </summary>
        internal static string zh_CHSFormat {
            get {
                return ResourceManager.GetString("zh-CHSFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 框架.
        /// </summary>
        internal static string zh_CHSFrames {
            get {
                return ResourceManager.GetString("zh-CHSFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 帮助.
        /// </summary>
        internal static string zh_CHSHelp {
            get {
                return ResourceManager.GetString("zh-CHSHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 图像.
        /// </summary>
        internal static string zh_CHSImage {
            get {
                return ResourceManager.GetString("zh-CHSImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 布局.
        /// </summary>
        internal static string zh_CHSLayout {
            get {
                return ResourceManager.GetString("zh-CHSLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 宏.
        /// </summary>
        internal static string zh_CHSMacros {
            get {
                return ResourceManager.GetString("zh-CHSMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 项目.
        /// </summary>
        internal static string zh_CHSProject {
            get {
                return ResourceManager.GetString("zh-CHSProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 查询.
        /// </summary>
        internal static string zh_CHSQuery {
            get {
                return ResourceManager.GetString("zh-CHSQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 查询设计器.
        /// </summary>
        internal static string zh_CHSQuery_Designer {
            get {
                return ResourceManager.GetString("zh-CHSQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 重构.
        /// </summary>
        internal static string zh_CHSRefactor {
            get {
                return ResourceManager.GetString("zh-CHSRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 报表.
        /// </summary>
        internal static string zh_CHSReport {
            get {
                return ResourceManager.GetString("zh-CHSReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 资源.
        /// </summary>
        internal static string zh_CHSResources {
            get {
                return ResourceManager.GetString("zh-CHSResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 架构.
        /// </summary>
        internal static string zh_CHSSchema {
            get {
                return ResourceManager.GetString("zh-CHSSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 样式.
        /// </summary>
        internal static string zh_CHSStyles {
            get {
                return ResourceManager.GetString("zh-CHSStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 表.
        /// </summary>
        internal static string zh_CHSTable {
            get {
                return ResourceManager.GetString("zh-CHSTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 表设计器.
        /// </summary>
        internal static string zh_CHSTable_Designer {
            get {
                return ResourceManager.GetString("zh-CHSTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 工作组.
        /// </summary>
        internal static string zh_CHSTeam {
            get {
                return ResourceManager.GetString("zh-CHSTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 测试.
        /// </summary>
        internal static string zh_CHSTest {
            get {
                return ResourceManager.GetString("zh-CHSTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 工具.
        /// </summary>
        internal static string zh_CHSTools {
            get {
                return ResourceManager.GetString("zh-CHSTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 视图.
        /// </summary>
        internal static string zh_CHSView {
            get {
                return ResourceManager.GetString("zh-CHSView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 窗口.
        /// </summary>
        internal static string zh_CHSWindow {
            get {
                return ResourceManager.GetString("zh-CHSWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XML.
        /// </summary>
        internal static string zh_CHSXML {
            get {
                return ResourceManager.GetString("zh-CHSXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 動作.
        /// </summary>
        internal static string zh_CHTAction {
            get {
                return ResourceManager.GetString("zh-CHTAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 增益集.
        /// </summary>
        internal static string zh_CHTAddins {
            get {
                return ResourceManager.GetString("zh-CHTAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 分析.
        /// </summary>
        internal static string zh_CHTAnalyze {
            get {
                return ResourceManager.GetString("zh-CHTAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 建置.
        /// </summary>
        internal static string zh_CHTBuild {
            get {
                return ResourceManager.GetString("zh-CHTBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 類別圖表.
        /// </summary>
        internal static string zh_CHTClass_Diagram {
            get {
                return ResourceManager.GetString("zh-CHTClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 社群.
        /// </summary>
        internal static string zh_CHTCommunity {
            get {
                return ResourceManager.GetString("zh-CHTCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 資料.
        /// </summary>
        internal static string zh_CHTData {
            get {
                return ResourceManager.GetString("zh-CHTData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 資料庫.
        /// </summary>
        internal static string zh_CHTDatabase {
            get {
                return ResourceManager.GetString("zh-CHTDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 資料庫圖表.
        /// </summary>
        internal static string zh_CHTDatabase_Diagram {
            get {
                return ResourceManager.GetString("zh-CHTDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 偵錯.
        /// </summary>
        internal static string zh_CHTDebug {
            get {
                return ResourceManager.GetString("zh-CHTDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 圖表.
        /// </summary>
        internal static string zh_CHTDiagram {
            get {
                return ResourceManager.GetString("zh-CHTDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 編輯.
        /// </summary>
        internal static string zh_CHTEdit {
            get {
                return ResourceManager.GetString("zh-CHTEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 檔案.
        /// </summary>
        internal static string zh_CHTFile {
            get {
                return ResourceManager.GetString("zh-CHTFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 格式.
        /// </summary>
        internal static string zh_CHTFormat {
            get {
                return ResourceManager.GetString("zh-CHTFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 框架.
        /// </summary>
        internal static string zh_CHTFrames {
            get {
                return ResourceManager.GetString("zh-CHTFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 說明.
        /// </summary>
        internal static string zh_CHTHelp {
            get {
                return ResourceManager.GetString("zh-CHTHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 影像.
        /// </summary>
        internal static string zh_CHTImage {
            get {
                return ResourceManager.GetString("zh-CHTImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 配置.
        /// </summary>
        internal static string zh_CHTLayout {
            get {
                return ResourceManager.GetString("zh-CHTLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 巨集.
        /// </summary>
        internal static string zh_CHTMacros {
            get {
                return ResourceManager.GetString("zh-CHTMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 專案.
        /// </summary>
        internal static string zh_CHTProject {
            get {
                return ResourceManager.GetString("zh-CHTProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 查詢.
        /// </summary>
        internal static string zh_CHTQuery {
            get {
                return ResourceManager.GetString("zh-CHTQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 查詢設計工具.
        /// </summary>
        internal static string zh_CHTQuery_Designer {
            get {
                return ResourceManager.GetString("zh-CHTQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 重整.
        /// </summary>
        internal static string zh_CHTRefactor {
            get {
                return ResourceManager.GetString("zh-CHTRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 報表.
        /// </summary>
        internal static string zh_CHTReport {
            get {
                return ResourceManager.GetString("zh-CHTReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 資源.
        /// </summary>
        internal static string zh_CHTResources {
            get {
                return ResourceManager.GetString("zh-CHTResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 結構描述.
        /// </summary>
        internal static string zh_CHTSchema {
            get {
                return ResourceManager.GetString("zh-CHTSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 樣式.
        /// </summary>
        internal static string zh_CHTStyles {
            get {
                return ResourceManager.GetString("zh-CHTStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 資料表.
        /// </summary>
        internal static string zh_CHTTable {
            get {
                return ResourceManager.GetString("zh-CHTTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 資料表設計工具.
        /// </summary>
        internal static string zh_CHTTable_Designer {
            get {
                return ResourceManager.GetString("zh-CHTTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 小組.
        /// </summary>
        internal static string zh_CHTTeam {
            get {
                return ResourceManager.GetString("zh-CHTTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 測試.
        /// </summary>
        internal static string zh_CHTTest {
            get {
                return ResourceManager.GetString("zh-CHTTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 工具.
        /// </summary>
        internal static string zh_CHTTools {
            get {
                return ResourceManager.GetString("zh-CHTTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 檢視.
        /// </summary>
        internal static string zh_CHTView {
            get {
                return ResourceManager.GetString("zh-CHTView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 視窗.
        /// </summary>
        internal static string zh_CHTWindow {
            get {
                return ResourceManager.GetString("zh-CHTWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XML.
        /// </summary>
        internal static string zh_CHTXML {
            get {
                return ResourceManager.GetString("zh-CHTXML", resourceCulture);
            }
        }
    }
}
